### PR TITLE
Improve documentation: make message queue cleaning clearer

### LINKED ISSUE #116: Message queue not empty at test start up
I don't know if this is a bug or a feature but without explicitly saying it, the message queue is at "module" scope (or even more global) which when using pytest (for example) is really annoying.

I'll illustrate it with the example from [dpytest doc](https://dpytest.readthedocs.io/en/latest/tutorials/using_pytest.html#starting-with-pytest) (only slightly modified: I renamed the `bot` fixture to `config_bot`: a weird habit of mine to always rename fixture object in test, feels like functions calls I guess :man_shrugging: )

```py
import discord
import discord.ext.commands as commands
from discord.ext.commands import Cog, command
import pytest
import pytest_asyncio
import discord.ext.test as dpytest


class Misc(Cog):
    @command()
    async def ping(self, ctx):
        await ctx.send("Pong !")

    @command()
    async def echo(self, ctx, text: str):
        await ctx.send(text)

@pytest_asyncio.fixture
async def config_bot():
    intents = discord.Intents.default()
    intents.members = True
    intents.message_content = True
    b = commands.Bot(command_prefix="!",
                     intents=intents)
    await b._async_setup_hook()  # setup the loop
    await b.add_cog(Misc())

    dpytest.configure(b)
    return b

@pytest.mark.asyncio
async def test_ping(config_bot):
    bot = config_bot
    await dpytest.message("!ping")
    assert dpytest.verify().message().content("Pong !")


@pytest.mark.asyncio
async def test_echo(config_bot):
    bot = config_bot
    await dpytest.message("!echo Hello world")
    assert dpytest.verify().message().contains().content("Hello")
```

as expected this example pass:
```
$ pytest
======================================= test session starts =======================================
platform linux -- Python 3.10.10, pytest-7.2.2, pluggy-1.0.0
rootdir: /tmp/dpytest
plugins: asyncio-0.21.0
asyncio: mode=strict
collected 2 items

test_dpytest_bug.py .. 

======================================== 2 passed in 0.24s ========================================
```

However just modifying a bit `test_ping` (sending two commands) will **crash `test_echo`** which seems weird: a test shouldn't influence another one:
```py
@pytest.mark.asyncio
async def test_ping(config_bot):
    bot = config_bot
    await dpytest.message("!ping")
    await dpytest.message("!ping")
    assert dpytest.verify().message().content("Pong !")
```

```
$ pytest
======================================= test session starts =======================================
[blabla]

test_dpytest_bug.py .F                                                                      [100%]

============================================ FAILURES =============================================
____________________________________________ test_echo ____________________________________________

config_bot = <discord.ext.commands.bot.Bot object at 0x7f9244d70490>

    @pytest.mark.asyncio
    async def test_echo(config_bot):
          [blablabla]

test_dpytest_bug.py:43: AssertionError
===================================== short test summary info =====================================
FAILED test_dpytest_bug.py::test_echo - AssertionError: assert <discord.ext.test.verify.VerifyMessage object at 0x7f9244d72200>
=================================== 1 failed, 1 passed in 0.34s ===================================
```

because the AssertionError dump isn't really clear (related to #115) I'll use `dpytest.get_message()` to debug my `test_echo` (the one which has crashed):
```py
@pytest.mark.asyncio
async def test_echo(config_bot):
    bot = config_bot
    await dpytest.message("!echo Hello world")
    print(dpytest.get_message().content)
    assert False
```

and we get:
```
$ pytest
======================================= test session starts =======================================
[blabla]

test_dpytest_bug.py .F                                                                      [100%]

============================================ FAILURES =============================================
____________________________________________ test_echo ____________________________________________
[blabla]
-------------------------------------- Captured stdout call ---------------------------------------
Pong !
===================================== short test summary info =====================================
FAILED test_dpytest_bug.py::test_echo - assert False
=================================== 1 failed, 1 passed in 0.34s ===================================_
```

Here we are: 
**in `test_echo` that doesn't call `!ping` tehre is a "Pong !" response in message queue** 

I'm aware of the `dpytest.empty_queue` to clear the message queue, but I'd expect the configuration from dpytest to be fucntion scoped. 
Ideally I'd like to call this `dpytest.empty_queue` in test teardown: for example after yielding `b` in the `config_bot` fixture but for some reason an async fixture can't yield and then teardown the test properly, at least I didn't manage to do it :confused: 

I'd really like your thoughts and help on that subject!

### PR DESCRIPTION
**Pull request by ctmbl**
Should fix #116 

According to me, this is the least that should be done to help the new user deal with message queue, the must would be to perform it automatically.

However I'm still not sure about a few changes:
- [ ] have I updated everything that should be?
- [ ] is there other queues that should be emptied? `send_queue`, `error_queue`?
- [ ] in #116 we didn't speak of the tuto without pytest but it should suffer the same issue right?
- [ ] I tried to improve the paragraph introducing fixture to talk about tear down/cleaning, which is what we're using here
- [ ] I added a troubleshooting case, the more explicit I could, to help future users that could encounter the issue I encountered

I separated my changes in different commits to help you walking through the reviewing process.

Don't hesitate to reject or discuss any changes I propose :wink:

### CODE REVIEW

**Comment by ctmbl** [comment]
@Sergeileduc

**Comment by Sergeileduc** [comment]
hmmm

I think the part in test_ping :
```python
    assert dpytest.verify().message().contains().content("Ping:")
    await dpytest.empty_queue() # empty the global message queue as test teardown
```
can be confusing, for new users.
It may lead to think "oh I should always put that line in my tests"

We definitly need to warn users that this problem can occur, and provide that information, but I think it would be better if it's after the "basic use case" without it.

I think we can keep the examples simple and straightforward, as they are, and right after, write somethint like "one problem that could happen is that the sent_queue is shared between the tests, so in order to not mess between your tests (verify() pops one message from the queue, so in general, you won't need to do anything, but if you have any issues, you can explicitly call empty_queue, as shown in the next example (and later, in the conftests.py)

something like that, I think

**Comment by ctmbl** [comment]
@Sergeileduc 

I really like you're idea! I'll change it that way

**Comment by Sergeileduc** [comment]
@ctmbl yeah, it's OK, '-' will make a bulleted list

I'll add the makefile and make.bat for the doc, so everyone can build and test

And the tasks for invoke, so you'll just need to type `inv doc` to build and open the doc in your browser
(well, if you pip install Sphinx and invoke, of course, but I think they are in the dev-requirements.txt)

**Pull request merged**
