### PR TITLE
Squashed commit of the following:

### PR DESCRIPTION
**Pull request by bravosierra99**
Change verify_message to allow peeking of messages and checking if messages *contain* text.  Added get_message to allow the tester to more easily retrieve messages sent from the bot.

### CODE REVIEW

**Comment by bravosierra99** [comment]
hey, wanted to check on this.  I was looking at adding other functionality to your test suite (ability to add attachments to a message and stuff)  Don't want to get too far if you have other plans or don't want to accept pull requests.  Could you let me know what you are thinking?  Thanks.

**Comment by bravosierra99** [comment]
this has issues if the bot returns more than one message, basically they get out of order, still thinking about how to fix it.

**Comment by CraftSpider** [comment]
Apologies for the delay, I have been busy with other projects. And yeah, messages getting out of order is a problem. Not sure off the top of my head how best to fix it, if there's an asyncio implementation of other data structures, one of those might be better

**Comment by bravosierra99** [comment]
so I fixed the naive way... just always pop them all and put them back in the proper order...   I think this might be ok?  It's definitely not ideal but it does work, and I'm trying to picture the case where you are going to get a significant amount of messages (and hence this might spiral out of control).  Let me know what you think about that and I can submit a new pull request.  I've also made a few other modifications in different areas.  I don't know if you are looking for additions or not, and if you have a way you would like it done.  Just let me know and I'll work on submitting them.

**Pull request closed without merging**
