### PR TITLE
fix for #27, 

### LINKED ISSUE #27: issue with event loop not completing on_error task
so I'm running into an issue with runner.py!message (line 264).  I don't think it's anything I've caused but I could be wrong.  My command is properly throwing a BadArgument Error, which is getting dispatched to the "on_error" event as a task in the event_loop.  However, by the time line 272 of runner.py finishes and it goes to line 274, the Task has NOT completed.  I can see it in the list by doing asyncio.all_tasks().  This causes the error_queue.empty() call to be true, which should not be the case.  So it appears there is some issue with making sure Tasks that are created during the execution of a command are actually completed.

### PR DESCRIPTION
**Pull request by bravosierra99**
closes #27 
I'm not super happy with this, but it does seem to work.
I'm not familiar with async enough to come up with a more graceful way
to catch tasks that are created after this function begins running.
when I read the code I feel like there are the proper "awaits" to ensure
that the task is complete prior to getting here... but I'm clearly wrong

### CODE REVIEW

**Comment by bravosierra99** [comment]
closing to hopefully rerun travis...

**Comment by bravosierra99** [comment]
ok that's twice it's failed on python 3.6, which I believe the function I'm mucking about with has changes between 3.6 and 3.6+.  I could probably download a 3.6 and try and see what's going on.

**Comment by bravosierra99** [comment]
ok I'm getting my Travis CI set up so that I can run my own tests....

**Comment by bravosierra99** [comment]
so I'm not even seeing the things I changed as being run in your tests??  so I'm not really sure what I'm doing wrong here...  I'm downloading a 3.6 to try and run it local...

**Comment by bravosierra99** [comment]
ok so the issue is that the task is considered done... but is staying in the loop.  But only on 3.6 apparently?

**Comment by bravosierra99** [comment]
sorry about the spam... I have travis set up for myself now, so in the future I'll do tests in my fork before they get pushed here...

**Comment by bravosierra99** [comment]
so thats interesting, because it passes in my fork...

**Comment by bravosierra99** [comment]
ah, I had not merged everything from you in, it looks like this might be related to your recent commits?  or the interaction between the two.

**Comment by bravosierra99** [comment]
yea so it looks like it's failing with the same error you got on your last push.  It's passing in my branch back in my fork.  So I'm going to say this guys is ready for your review now.  Sorry again for all the spam and such as I'm learning this workflow.  In the future I'll attempt to work off stable commits from you, work them in my own branch, and I'll pass tests in my own fork before requesting a pull request.

**Comment by Sergeileduc** [comment]
I don't know if it can be usefull, but when I proposed my PR (which is based on 2 of your commits), what I did was :

- add your repository to be a "remote" in my local environnement dev for dpytest
something like :
`git remote add bravo https://github.com/uXXXXX.git`
(yeah, I named your remote bravo, so I don't get confuse)

- cherry-pick some of your commits in my branch with `git cherry-pick <commitSha>`

I don't know if it can help you. Let me know !

**Comment by bravosierra99** [comment]
interesting... had no idea you could do that....  That sounds super handy!

**Pull request closed without merging**
