### PR TITLE
Improve CI, report coverage (correctly) and more

### PR DESCRIPTION
**Pull request by shahoob**
I intend this PR to improve the Test CI workflow a bit.

- It should only run when code is changed (not just on every push on anything)
- It also reports coverage and uploads it in multiple formats

It also seems like coverage doesn't pick up the files when provided whereas if it's a path. (`--source=discord/ext/test` collects nothing)
I examined the source code and tried passing `discord.ext.test` to `--source`, which worked and was able to collect data.
However, the filenames in the report are pointing inside the Python installation being used, which when used with a service that tracks code coverage, may mess things up.

Should I figure out how to remove those things automatically? coverage also has an [API for modifying the DB](https://coverage.readthedocs.io/en/6.5.0/api_coveragedata.html#coverage.CoverageData).

### CODE REVIEW

**Comment by Sergeileduc** [comment]
seems nice !

```- name: Upload HTML report
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ matrix.python-version }}-cov-htmlcov
        path: htmlcov
        if-no-files-found: warn
```

It uploads the coverage result as assets, in the release ? right ? I'm not super familiar how this works ?

**Comment by shahoob** [comment]
it doesn't upload into the release. it instead uploads it as a build artifact.
it's accessible from a workflow run's summary page. ([example](https://github.com/CraftSpider/dpytest/actions/runs/3641180728))

it doesn't stay there forever though and will expire after its retention period is exceeded.
you can always rerun a workflow though.

**Comment by Sergeileduc** [comment]
ho okay, I just tested it (download an artifact, a coverage html, and open it. works fine !)

(although normally I use my `invoke` command `inv coverage` to have it locally.

But yeah, it's nice !

Thank you !

**Comment by shahoob** [comment]
you're welcome!

but still, the coverage report's filenames still refers to somewhere in the Python installation being used.

**Comment by shahoob** [comment]
update: [`invoke`](https://pypi.org/project/invoke/) does not classify to PyPI that it supports python v3.10 and later, even though the README says otherwise.

it definitely won't work with python 3.11.

**Comment by Sergeileduc** [comment]
@shahoob no no the thing you did is perfect !

I just mentioned invoke in my "local" dev setup. Much easy to call `inv coverage`, on my computer.

But for things that can be scripted, like github actions, let's go with the regular command line, of course.

**Comment by shahoob** [comment]
got it @Sergeileduc

i also setup linting and it does work but the problems should be fixed in order for it to be green.
flake8 unfortunately can't autofix linting violations currently.

**Comment by shahoob** [comment]
i'll see if i can do caching in the workflow

**Comment by shahoob** [comment]
@Sergeileduc
The stuff in this PR is ready to be merged

However, I have committed many commits, and this may clog up the commit history.
You can squash merge this PR instead. Or i can rebase my fork and squash my commits into fewer ones.

**Comment by Sergeileduc** [comment]
Yeah, squash and merge sounds great !

the linting job is great too, thank you.

it will help with future PR, to have a "clean code".

but yeah, next thing we should do is lint the code, so it pass our own linting github action.

**Review by Sergeileduc — APPROVED** [review]

**Pull request merged**
