### PR TITLE
Fix linting violations and coverage reporting

### PR DESCRIPTION
**Pull request by shahoob**
- only run lint ci when files that are to be linted are changed
- make flake8 mostly happy
- fix test coverage reporting

### CODE REVIEW

**Comment by shahoob** [comment]
@Sergeileduc you may review the changes and merge accordingly

**Comment by Sergeileduc** [comment]
OK.

I usually not in the "mix commits for CICD and for other sutffs in a single PR"

But let's do it.

**Comment by shahoob** [comment]
@Sergeileduc do you want me to create 2 seperate PRs for the changes?
this PR is closed and it's changes are not present in the repo

**Comment by Sergeileduc** [comment]
@shahoob next time !

**Comment by shahoob** [comment]
ok

**Pull request closed without merging**
