### PR TITLE
Fix verify_emebd.

### PR DESCRIPTION
**Pull request by Sergeileduc**
Hi !

Fist of all, thanks for the lib ! It's really cool to be able to unit test his cogs, etc...

I propose this PR.

##  Why this PR ?

I had troubles testing "embeds".
Turns out the verify_embed uses `assert embed1 == embed2`
And it turns out that discord.embed.Embed has no `__eq__` method
I wasn't able to use verify_embed.

##  What it changes :

So I made this.
Just defining a simple `__eq__` for Embeds objects (it tests title, description, url, image_url, fields), and it works fine.

##  Other things
I also add a couple of "return" call, in the `assert_nothing` cases, because we shouldn't use `message = sent_queue.get_nowait()` in the case `sent_queue.qsize() == 0`

### CODE REVIEW

**Comment by CraftSpider** [comment]
Not sure how I feel about overriding __eq__, over just using embed_eq in the assertions. While this library does a lot of dynamic alteration of classes, I'd prefer to not do it where it isn't necessary

**Comment by Sergeileduc** [comment]
> Not sure how I feel about overriding **eq**, over just using embed_eq in the assertions. While this library does a lot of dynamic alteration of classes, I'd prefer to not do it where it isn't necessary

Sure. As you prefer.
So we should just use `embed_eq` in those two asserts ?

```python3
if equals:
    assert emb == embed, "Didn't find expected embed"
else:
    assert emb != embed, "Found unexpected embed"
```

in `verify_embed` ?

I'll do that and will open another PR, if you want.

Also, I defined those `embed_eq` methods in `enhance.py`, cause I didn't want to mess with the way you organize your files, but I don't know if you prefer to put those in another file ?

**Comment by CraftSpider** [comment]
Yes, I'd use the comparison in asserts. I personally would have called the file utils, but the placement looks fine as-is to me

**Comment by Sergeileduc** [comment]
Ok, I commited requested changes (no more overriding `embed.__eq__`)

And new file is renamed `utils.py`

**Comment by CraftSpider** [comment]
Looks nice, thank you for your patience

**Pull request merged**
