### PR TITLE
Feature/additional functionality

### PR DESCRIPTION
**Pull request by bravosierra99**
a variety of added functionality, and some bug fixes.  I've submitted some of these bug fixes in other PR's.  This contains all of my current work.

### CODE REVIEW

**Comment by Circlepuller** [comment]
Gotta say, I'm really impressed with your work on this. Hopefully it gets merged in as I'd love to keep using this for my bots

**Comment by Sergeileduc** [comment]
Great job !

Travis CI fails because of `websocket` in `configure` :

This is propably due to the fact that discord.py 1.4 recently replace `websockets` with `aiohttp.ws` :
https://discordpy.readthedocs.io/en/latest/whats_new.html#miscellaneous
(or maybe not, I don't know for sure)

```console
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/runner.py:354: in configure
    back.configure(client)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/backend.py:753: in configure
    ws = websocket.FakeWebSocket()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <discord.ext.test.websocket.FakeWebSocket object at 0x7f3a8abe76d8>
args = (), kwargs = {}
    def __init__(self, *args, **kwargs):
>       super().__init__(*args, **kwargs)
E       TypeError: __init__() missing 1 required positional argument: 'socket'
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/websocket.py:10: TypeError
```

**Comment by Sergeileduc** [comment]
Ok, so I tried a few things, to suppress one error at a time.

I give you the details, if you want to test it and/or implement these.

So for the current error, when running tests :
```console
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/runner.py:354: in configure
    back.configure(client)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/backend.py:753: in configure
    ws = websocket.FakeWebSocket()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <discord.ext.test.websocket.FakeWebSocket object at 0x7f3a8abe76d8>
args = (), kwargs = {}
    def __init__(self, *args, **kwargs):
>       super().__init__(*args, **kwargs)
E       TypeError: __init__() missing 1 required positional argument: 'socket'
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/discord/ext/test/websocket.py:10: TypeError
```

What I did is change this line :
```python
    ws = websocket.FakeWebSocket()
```
https://github.com/bravosierra99/dpytest/blob/319a77d7a6bf0b0c20488692a73ca72d314ce0eb/discord/ext/test/backend.py#L753
with :
```python
    ws = websocket.FakeWebSocket(None, loop=loop)
```
I think it may work, I don't know for sure (but the signature is right, so we can see later).

After that, the error is solved (no more `missing positional argument`, but it throws a new error) :
```console
class FakeState(dstate.ConnectionState):
    def __init__(self, client, http, user=None, loop=None):
        if loop is None:
            loop = asyncio.get_event_loop()
>       super().__init__(dispatch=client.dispatch, chunker=client._chunker, handlers=None, syncer=None, http=http,
                         loop=loop)
E       AttributeError: 'Bot' object has no attribute '_chunker'

discord/ext/test/state.py:13: AttributeError
```

So I looked at `discord.state ConnectionState` :
```python
class ConnectionState:
    def __init__(self, *, dispatch, handlers, hooks, syncer, http, loop, **options):
```

So what I did was :

Replace your line :
```python
        super().__init__(dispatch=client.dispatch, chunker=client._chunker, handlers=None, syncer=None, http=http, loop=loop)
```
https://github.com/bravosierra99/dpytest/blob/319a77d7a6bf0b0c20488692a73ca72d314ce0eb/discord/ext/test/state.py#L13
with :
```python
        super().__init__(dispatch=client.dispatch,
                         handlers=None, hooks=None,
                         syncer=None, http=http,
                         loop=loop)
```
Once again, it solves the error, but the tests still fail, with this error :

```console
            data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
>                                                                     nonce=nonce, allowed_mentions=allowed_mentions)
E           TypeError: send_message() got an unexpected keyword argument 'allowed_mentions'

.venv/lib/python3.7/site-packages/discord/abc.py:891: TypeError
```

So that's what I found, so far.

Not sure if this will eventually work (I initialized some things to None, maybe they are required, I don't know...) The signature is right, though, so we can investigate that later.

I have no clue, for the `allowed_mentions` error, though.

Feel free to test if you want, and commit if you want to !

See yah

**Comment by Sergeileduc** [comment]
Ok, found it :
`backend.py` line 109 :

```python
    async def send_message(self, channel_id, content, *, tts=False, embed=None,
                           nonce=None, allowed_mentions=None):
```

I checked out your branch, and add the three fixes, and tried a PR

(obviously, your work is still yours, and the commits you made are still yours)

I want to see if it passes Travis (it pass pytest on my machine)

**Comment by Sergeileduc** [comment]
It pass Travis CI, guys !

GG all !

**Comment by Circlepuller** [comment]
Now it's just a matter of having these PRs merged. Hoping for the best!

**Comment by Sillocan** [comment]
Just testing with v1.4.1 of `discord.py`, this PR also handles #33.

**Comment by CraftSpider** [comment]
Hi, thanks for your patience everyone. This project kind of fell by the wayside, but I really appreciate the effort put into this. I did a quick review and it looks good, I'm willing to trust both Travis and the fact that several of you also did your own reviews. Thank you all, I'll release a new version d.py once I have the time.

**Pull request merged**
