### PR TITLE
Docs: Add vertical spacing for functions & methods

### LINKED ISSUE #59: Add spacing for docs function
Right now it's suffocating

image

Maybe something like
```css
.py.function {
    margin-bottom: 50px;
}

.py.method {
    margin-bottom: 30px;
}
```

image

### PR DESCRIPTION
**Pull request by DleanJeans**
Closes #59

### CODE REVIEW

**Comment by CraftSpider** [comment]
Can you add a picture of how the docs look now, or a link to them rendered? If not I'll do it myself when I have the time.

**Comment by itsTheFae** [comment]
The changes here look a like this:  Screenshot 2021-07-06 065205

Certainly a step in the right direction.

**Comment by CraftSpider** [comment]
Thank you, and I definitely agree. I'm good with merging as long as @Sergeileduc has no issues with this.

**Comment by DleanJeans** [comment]
Just noticed, we have 2 Factories pages here:

image

The bottom one should be WebSocket.
So another PR? xD

**Pull request merged**
